/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/authentication',
        'getting-started/base-url',
        'getting-started/errors',
        'getting-started/pagination',
      ],
    },
    {
      type: 'category',
      label: 'User Management',
      items: [
        'user-management/users',
        'user-management/user-files',
        'user-management/user-certificates',
        'user-management/user-educations',
        'user-management/user-languages',
        'user-management/user-professions',
        'user-management/user-right-to-works',
        'user-management/user-skills',
        'user-management/user-career-history',
        'user-management/user-skill-passports',
        'user-management/user-subscription',
        'user-management/user-salary-country',
        'user-management/user-interests',
        'user-management/encrypted-user-data',
        'user-management/user-accounts',
        'user-management/user-role-assignments',
      ],
    },
    {
      type: 'category',
      label: 'Job Management',
      items: [
        'job-management/jobs',
        'job-management/job-steps',
        'job-management/applicants',
        'job-management/applicant-steps',
        'job-management/applicant-legal-files',
        'job-management/applicant-job-steps',
        'job-management/skill-match',
      ],
    },
    {
      type: 'category',
      label: 'Company Management',
      items: [
        'company-management/companies',
        'company-management/company-files',
        'company-management/departments',
        'company-management/industries',
        'company-management/follow-user-to-companies',
        'company-management/public-companies',
      ],
    },
    {
      type: 'category',
      label: 'Social & Communication',
      items: [
        'social-communication/posts',
        'social-communication/events',
        'social-communication/event-pakets',
        'social-communication/groups',
        'social-communication/group-members',
        'social-communication/follow-user-to-user',
        'social-communication/feedbacks',
        'social-communication/notifications',
      ],
    },
    {
      type: 'category',
      label: 'Master Data',
      items: [
        'master-data/schools',
        'master-data/school-majors',
        'master-data/majors',
        'master-data/languages',
        'master-data/professions',
        'master-data/skills',
        'master-data/licenses',
        'master-data/regions',
        'master-data/right-to-works',
        'master-data/subscription-plans',
        'master-data/tags',
        'master-data/interests',
        'master-data/salary-countries',
        'master-data/countries',
      ],
    },
    {
      type: 'category',
      label: 'Data Mappings',
      items: [
        'data-mappings/education-license-mappings',
        'data-mappings/education-profession-mappings',
        'data-mappings/license-skill-mappings',
        'data-mappings/informal-certificate-mappings',
        'data-mappings/pending-student-verifications',
      ],
    },
    {
      type: 'category',
      label: 'System & Admin',
      items: [
        'system-admin/rbac',
        'system-admin/configs',
        'system-admin/media',
        'system-admin/fields',
        'system-admin/questionnaires',
        'system-admin/questionnaire-answers',
        'system-admin/invoices',
        'system-admin/invoice-items',
        'system-admin/bulk-upload',
        'system-admin/data-migration',
        'system-admin/email-queue-monitoring',
      ],
    },
  ],
};

module.exports = sidebars;
